# Generated by Django 6.0.2 on 2026-02-28 01:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('ish_vaqti', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=200)),
                ('t_sana', models.DateField(blank=True, null=True)),
                ('kitob_soni', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tirik', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('guruh', models.CharField(max_length=50)),
                ('kurs', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('kitob_soni', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('janr', models.CharField(max_length=100)),
                ('sahifa', models.PositiveSmallIntegerField()),
                ('muallif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.muallif')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('qaytargan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.kitob')),
                ('kutubxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.kutubxonachi')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.talaba')),
            ],
        ),
    ]
