# Generated by Django 6.0.2 on 2026-02-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talaba',
            name='title',
        ),
        migrations.AlterField(
            model_name='talaba',
            name='guruh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kitob_soni',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
